### ISSUE TITLE
issue with the api key

### ISSUE THREAD

**Issue by balouzza** [ikhebgeenaccount/Excel-Match-History-Analyzer#1]
when i type in the api , it get erased automatically and te word "saved!" is written.
My version of office is 2016 and on win10

**Comment by ikhebgeenaccount** [comment]
The api key should be overwritten by the word "Saved!". Does cell D6 say "No API key set?".

**Comment by balouzza** [comment]
I just retried and it doesn't , although now when i excel take up to 50% of process power and do nothing. No error message whatsoever.

**Comment by balouzza** [comment]
nevermind ! maybe my computer is just shitty , because i tried to be patient and after a good while it finally worked.
Great job , keep it up ! :D
