### ISSUE TITLE
api key not recognized?

### ISSUE THREAD

**Issue by krizmac** [ikhebgeenaccount/Excel-Match-History-Analyzer#2]
I'm typing my api key into cell C6 and the sheet is returning "API Key not set"

Am I just missing something small here?

**Comment by ikhebgeenaccount** [comment]
Have you enabled macros?

**Comment by krizmac** [comment]
Aye. Maybe since I am trying to open this with OpenOffice's version of Excel things are not working properly.

**Comment by ikhebgeenaccount** [comment]
[The sheet does not work with anything other than Microsoft Excel 2010 or higher](https://github.com/ikhebgeenaccount/Excel-Match-History-Analyzer/issues/2#issuecomment-197652885). Sorry!
