### ISSUE TITLE
Longest game only displaying default 00:00:00

### ISSUE THREAD

**Issue by raitono** [ikhebgeenaccount/Excel-Match-History-Analyzer#3]
The longest game cell(C16) isn't being shown correctly. Looking in the General Stats sheet, I also see that the Sec combined column(AN) is not being populated. I am using Excel 2013 32-bit and am on version 1.5 of the Analyzer. Everything else seems to be working fine with the exception that the lane opponent or position is sometimes wrong, but that would be a Riot API problem.

**Comment by ikhebgeenaccount** [comment]
Thanks for the report, will be fixed in next update. For now, to get it working:
1. Insert `=AL3*(BA3=Summoner)*(C3<>"Bot")*(C3<>"Custom")` in cell `AN3`
2. Drag down until last game
