### ISSUE TITLE
Error The URL is invalid

### ISSUE THREAD

**Issue by TheRealVincentVanGogh** [ikhebgeenaccount/Excel-Match-History-Analyzer#4]
Just downloaded this sheet and opened it, did the installation process and i hit update and this message appears: 
![capture](https://cloud.githubusercontent.com/assets/19521118/17043755/c48a49c6-4f6e-11e6-84fc-da31ce7ffacd.PNG)

**Comment by ikhebgeenaccount** [comment]
Use the shorthand for the region, so 'na' instead of 'North America'
