### ISSUE TITLE
Microsoft Visual basic error

### ISSUE THREAD

**Issue by Firefighter4Cy** [ikhebgeenaccount/Excel-Match-History-Analyzer#6]
When I select update the following message comes up: Microsoft Visual Basic Run-time Error '-2147012889 (80072ee7)': The server name or address could not be resolved
When I click debug on that dialog box it opens microsoft visual basic and shows a yellow highlighted text that says:
MyRequest.Send

![image](https://user-images.githubusercontent.com/11983797/29144261-e55048ee-7d1d-11e7-813f-b4d2aecffcb2.png)
![image](https://user-images.githubusercontent.com/11983797/29144438-a3b1803c-7d1e-11e7-822f-e55357c56a4f.png)

**Comment by Firefighter4Cy** [comment]
I don't see any solution.

**Comment by raitono** [comment]
Riot recently did some pretty big API changes and deprecated some stuff. The url this was using may not be available anymore and that's why you're getting the message.

**Comment by ikhebgeenaccount** [comment]
That's exactly what happened. I marked this as resolved as you also reached out to me on reddit and I answered you there @Firefighter4Cy.
