### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by Rusoraiteri** [ikhebgeenaccount/Excel-Match-History-Analyzer#7]
![Captura de pantalla 2021-05-10 174009](https://user-images.githubusercontent.com/83984901/117721974-e4757800-b1b6-11eb-8c96-9252032e5aee.png)

**Comment by ikhebgeenaccount** [comment]
Spreadsheet has not been updated for the changes made to the Riot API in summer 2017 and will not be (by me at least).
