### ISSUE TITLE
Error :/

### ISSUE THREAD

**Issue by Hirozashi0** [ikhebgeenaccount/Excel-Match-History-Analyzer#8]
Hello, First of all I want to thank you for doing something like this because it's a mega useful thing :D but unfortunately I'm having a little trouble with it, after filling in everything as it is in the instructions I get this error pops up :/ if it's necessary I can make more screenshots or I can also provide a discord to make it more convenient to communicate. Since i dont know why error pops in my native language (polsih) i translated this one for you :c
![error match analyzer](https://github.com/ikhebgeenaccount/Excel-Match-History-Analyzer/assets/162927386/6aa8fec4-2d53-4d22-853f-f16659b0e580)

**Comment by Hirozashi0** [comment]
When i click on debug its sending me to this tab

![obraz_2024-03-10_234859363](https://github.com/ikhebgeenaccount/Excel-Match-History-Analyzer/assets/162927386/58aecb8c-8f82-43f1-bbcb-bf0a50960bce)

**Comment by ikhebgeenaccount** [comment]
Hi, unfortunately, since Riot's changes to their API in 2017, the spreadsheet doesn't work anymore. I'm sure you'll be able to scratch your statistics itch through resources such as op.gg, leagueofgraphs or porofessor. Thanks for your interest!
